### PR TITLE
Incubator - NFS Provisioner - Change pvc storage class setup

### PR DESCRIPTION
**Pull request by alebabai**
## what
* Use `storageClassName ` rather than annotation

## why
* The annotation `volume.alpha.kubernetes.io/storage-class` simply don't work for K8s 1.8 and higher.
* The annotation `volume.beta.kubernetes.io/storage-class` still working, but:
> In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release.

## references
* https://kubernetes.io/docs/concepts/storage/persistent-volumes/

### CODE REVIEW

**Comment by osterman** [comment]
@goruha can you take a look at this? thanks!

**Comment by osterman** [comment]
@goruha is back in the office and will take a look.

**Comment by alebabai** [comment]
got it, thanks for the update

ср, 7 февр. 2018 г., 20:09 Erik Osterman <notifications@github.com>:

**Comment by alebabai** [comment]
Hi,
Are there any news about this changes?

**Comment by osterman** [comment]
A little progress. We had to fix our CI to support external PRs. That's working now. @goruha please have a look again.

**Comment by alebabai** [comment]
@goruha is it okay for you now?

**Pull request merged**
